Repository hackerai-tech/PentestGPT, pull requests merged in 2024-02, with the labels that each got.

#15 feat: restore subscription
  .env.local.example
  app/api/stripe/webhook/route.ts
  components/utility/global-state.tsx
  components/utility/plan-dialog.tsx
  components/utility/profile-tabs/subscription-tab.tsx
  context/context.tsx
  db/subscriptions.ts
  lib/result.ts
  lib/server/restore.ts
  lib/server/stripe-url.ts
  lib/server/stripe.ts
  lib/utils.ts
Labels: enhancement

#52 42 implement secure transformation of unsupported file formats into text for ai processing
  app/api/retrieval/process/route.ts
  components/chat/chat-hooks/use-select-file-handler.tsx
  components/chat/chat-input.tsx
  components/chat/dialog-portal.tsx
  components/ui/dashboard.tsx
  lib/retrieval/processing/convert.ts
  lib/retrieval/processing/index.ts
Labels: enhancement, Security 🛡️

#57 Implemented immediate streaming logic for HackerGPT v1 plugins endpoint response.
  app/api/chat/plugins/route.ts
Labels: AI efficacy
